# Generated by Django 6.0.3 on 2026-08-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_tag_blog_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name'], 'verbose_name_plural': 'categories'},
        ),
    ]
